# Generated by Django 4.2 on 2024-02-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_remove_user_name_user_birthday_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client'), ('store', 'Store'), ('deliveryman', 'Deliveryman')], default='client', max_length=50),
        ),
    ]
